name: "Test requests"
 
on:
  push:
    branches: [main]
 
jobs:
  run-updater:
    runs-on: ubuntu-latest
    steps:
    - name: homepage request
      run: |
        curl -X GET "https://http-me.edgecompute.app/"
