name: "Test requests with ngwaf"
 
on:
  push:
    branches: [main]

 # https://docs.fastly.com/en/ngwaf/installing-the-agent-on-ubuntu#install-and-configure-the-signal-sciences-agent-package
 # sudo service sigsci-agent start

  run-waf-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
    - name: Set up Fastly CLI
      uses: fastly/compute-actions/setup@v5
      run: |
        fastly compute serve &
        curl -si -X GET "http://0.0.0.0:7676/anything/from-gh-action-c-and-e"
    - name: install ngwaf
      run: |
       sudo apt-get update
       sudo apt-get install -y apt-transport-https wget gnupg
       wget -qO - https://apt.signalsciences.net/release/gpgkey | sudo gpg --dearmor -o /usr/share/keyrings/sigsci.gpg
       sudo echo "deb [signed-by=/usr/share/keyrings/sigsci.gpg] https://apt.signalsciences.net/release/ubuntu/ jammy main" | sudo tee /etc/apt/sources.list.d/sigsci-release.list
       sudo apt-get update
       sudo apt-get install sigsci-agent
    - name: start ngwaf
      env:
       SIGSCI_ACCESSKEYID: ${{ secrets.ACCESSKEYID }}
       SIGSCI_SECRETACCESSKEY: ${{ secrets.SECRETACCESSKEY }}
       SIGSCI_REVPROXY_LISTENER: "app1:{listener=http://0.0.0.0:8888,upstreams=https://http-me.edgecompute.app:443/,pass-host-header=false}"
      run: |
        /usr/sbin/sigsci-agent &
        ps
    - name: homepage request
    # curl -X GET "https://http-me.edgecompute.app/"
      run: |
        curl -si -X GET "http://0.0.0.0:8888/anything/from-gh-action"
        
    - name: stop ngwaf
      run: |
        killall sigsci-agent
        ps
        
    
    
